# Generated by Django 5.2.8 on 2026-09-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
