# Generated by Django 5.2.8 on 2026-09-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_phoneverification_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneverification',
            old_name='expaires_at',
            new_name='expires_at',
        ),
    ]
