# Generated by Django 5.2.8 on 2026-10-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_phoneverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='purpose',
            field=models.CharField(choices=[('registration', 'ثبت نام'), ('password_reset', 'بازیابی کلمه عبور'), ('change_phone', 'تغییر شماره موبایل')], default='registration', max_length=20),
        ),
    ]
